# Generated by Django 6.0.5 on 2026-06-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('create_date',)},
        ),
    ]
