# Generated by Django 6.0.5 on 2026-06-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_pic',
            field=models.ImageField(default='blog/blog1.jpeg', upload_to='blog/% Y/% m/'),
        ),
    ]
