# Generated by Django 6.0.5 on 2026-06-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_main_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_pic',
            field=models.ImageField(default='blog/blog1.jpeg', upload_to='blog/'),
        ),
    ]
