# Generated by Django 6.0.5 on 2026-06-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.ImageField(null=True, upload_to='')),
                ('cvlink', models.URLField(null=True)),
                ('about', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('certificator', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('academy', models.CharField(max_length=100)),
                ('time_start', models.CharField(max_length=100)),
                ('time_end', models.CharField(default='تاکنون', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobExperienceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('about', models.TextField(null=True)),
                ('time_start', models.CharField(max_length=100)),
                ('time_end', models.CharField(default='تاکنون', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
