# Generated by Django 6.0.5 on 2026-06-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinformation',
            name='cvlink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseinformation',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
