# Generated by Django 6.0.5 on 2026-06-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_baseinformation_cvlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinformation',
            name='profile',
            field=models.ImageField(null=True, upload_to='info/'),
        ),
    ]
