# Generated by Django 6.0.5 on 2026-06-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_baseinformation_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseinformation',
            name='cvlink',
        ),
        migrations.AddField(
            model_name='baseinformation',
            name='cv_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='baseinformation',
            name='github_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='baseinformation',
            name='linkedin_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='baseinformation',
            name='telegram_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='baseinformation',
            name='x_link',
            field=models.URLField(null=True),
        ),
    ]
