# Generated by Django 6.0.5 on 2026-06-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_baseinformation_cvlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinformation',
            name='cv_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseinformation',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseinformation',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseinformation',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baseinformation',
            name='x_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
