# Generated by Django 6.0.5 on 2026-06-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_baseinformation_cv_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinformation',
            name='cv_link',
            field=models.FileField(null=True, upload_to='info/doc/'),
        ),
    ]
