# Generated by Django 6.0.5 on 2026-06-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_baseinformation_cv_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseinformation',
            old_name='cv_link',
            new_name='cv',
        ),
        migrations.AlterField(
            model_name='baseinformation',
            name='profile',
            field=models.ImageField(default='info/defaultprofile.jpg', upload_to='info/'),
        ),
    ]
